apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deploy
  labels:
    app: movies
spec:
  replicas: 2
  selector:
    matchLabels:
      labels:
        app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
       containers:
         name: cont1
        - image: saibootla/paytmmoviesrepo:latest
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 80
